# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-17 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190817_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='DELL XPS 9570', max_length=100),
            preserve_default=False,
        ),
    ]
