# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190818_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
